title: Kate in Context
theme: minima
collections:
  collection:
    output: true


defaults:
  - scope:
      type: "collection"
    values:
      layout: collection_item

Author.name: Kate Erickson
Author.email: KeErickson95@gmail.com