title: Kate in Context
theme: minima
collections:
  collection:
    output: true


defaults:
  - scope:
      type: "collection"
    values:
      layout: collection_item

author: 
  name: Kate Erickson
  email: Contact@KateInContext.com

description: A site to get to know your next favorite information professional. 