title: Kate in Context
theme: minima
skin: dark
collections:
  projects:
    output: true


defaults:
  - scope:
      type: "projects"
    values:
      layout: subpage

author: 
  name: Kate Erickson
  email: Contact@KateInContext.com

description: Get to know your next favorite information professional. 

